-- HR Management Advanced Features

-- Recruitment (ATS) Tables
CREATE TABLE IF NOT EXISTS `job_postings` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `job_code` varchar(50) UNIQUE NOT NULL,
  `department_id` bigint(20) unsigned DEFAULT NULL,
  `designation_id` bigint(20) unsigned DEFAULT NULL,
  `employment_type` enum('Full-Time','Part-Time','Contract','Internship') DEFAULT 'Full-Time',
  `experience_required` varchar(50) DEFAULT NULL,
  `qualification` text DEFAULT NULL,
  `skills_required` text DEFAULT NULL,
  `job_description` text DEFAULT NULL,
  `responsibilities` text DEFAULT NULL,
  `salary_range_min` decimal(12,2) DEFAULT NULL,
  `salary_range_max` decimal(12,2) DEFAULT NULL,
  `vacancies` int(11) DEFAULT 1,
  `location` varchar(200) DEFAULT NULL,
  `application_deadline` date DEFAULT NULL,
  `status` enum('Draft','Active','Closed','On Hold') DEFAULT 'Draft',
  `posted_by` bigint(20) unsigned DEFAULT NULL,
  `posted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `job_postings_department_id_foreign` (`department_id`),
  KEY `job_postings_designation_id_foreign` (`designation_id`),
  CONSTRAINT `job_postings_department_id_foreign` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `job_postings_designation_id_foreign` FOREIGN KEY (`designation_id`) REFERENCES `designations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `applicants` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `application_code` varchar(50) UNIQUE NOT NULL,
  `job_posting_id` bigint(20) unsigned NOT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `email` varchar(150) UNIQUE NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `gender` enum('Male','Female','Other') DEFAULT NULL,
  `address` text DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `education` text DEFAULT NULL,
  `experience_years` decimal(5,2) DEFAULT 0.00,
  `current_company` varchar(200) DEFAULT NULL,
  `current_position` varchar(100) DEFAULT NULL,
  `current_salary` decimal(12,2) DEFAULT NULL,
  `expected_salary` decimal(12,2) DEFAULT NULL,
  `skills` text DEFAULT NULL,
  `resume_path` varchar(255) DEFAULT NULL,
  `cover_letter` text DEFAULT NULL,
  `linkedin_url` varchar(255) DEFAULT NULL,
  `portfolio_url` varchar(255) DEFAULT NULL,
  `status` enum('New','Screening','Interview','Assessment','Offer','Hired','Rejected','Withdrawn') DEFAULT 'New',
  `stage` varchar(100) DEFAULT 'Application Received',
  `rating` decimal(3,2) DEFAULT NULL COMMENT '1-5 rating',
  `notes` text DEFAULT NULL,
  `applied_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `applicants_job_posting_id_foreign` (`job_posting_id`),
  CONSTRAINT `applicants_job_posting_id_foreign` FOREIGN KEY (`job_posting_id`) REFERENCES `job_postings` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `interviews` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `applicant_id` bigint(20) unsigned NOT NULL,
  `interview_type` enum('Phone','Video','In-Person','Technical','HR','Final') DEFAULT 'In-Person',
  `scheduled_date` date NOT NULL,
  `scheduled_time` time NOT NULL,
  `duration` int(11) DEFAULT 60 COMMENT 'in minutes',
  `location` varchar(255) DEFAULT NULL,
  `meeting_link` varchar(255) DEFAULT NULL,
  `interviewer_id` bigint(20) unsigned DEFAULT NULL,
  `status` enum('Scheduled','Completed','Cancelled','No Show','Rescheduled') DEFAULT 'Scheduled',
  `feedback` text DEFAULT NULL,
  `rating` decimal(3,2) DEFAULT NULL,
  `result` enum('Passed','Failed','On Hold') DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `interviews_applicant_id_foreign` (`applicant_id`),
  KEY `interviews_interviewer_id_foreign` (`interviewer_id`),
  CONSTRAINT `interviews_applicant_id_foreign` FOREIGN KEY (`applicant_id`) REFERENCES `applicants` (`id`) ON DELETE CASCADE,
  CONSTRAINT `interviews_interviewer_id_foreign` FOREIGN KEY (`interviewer_id`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Onboarding Tables
CREATE TABLE IF NOT EXISTS `onboarding_checklists` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `department_id` bigint(20) unsigned DEFAULT NULL,
  `designation_id` bigint(20) unsigned DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `onboarding_checklists_department_id_foreign` (`department_id`),
  KEY `onboarding_checklists_designation_id_foreign` (`designation_id`),
  CONSTRAINT `onboarding_checklists_department_id_foreign` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `onboarding_checklists_designation_id_foreign` FOREIGN KEY (`designation_id`) REFERENCES `designations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `onboarding_tasks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `checklist_id` bigint(20) unsigned NOT NULL,
  `task_name` varchar(255) NOT NULL,
  `task_description` text DEFAULT NULL,
  `category` enum('Documentation','IT Setup','Access Rights','Training','Introduction','Compliance','Other') DEFAULT 'Documentation',
  `responsible_role` varchar(100) DEFAULT NULL,
  `days_to_complete` int(11) DEFAULT 1,
  `is_mandatory` tinyint(1) DEFAULT 1,
  `sort_order` int(11) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `onboarding_tasks_checklist_id_foreign` (`checklist_id`),
  CONSTRAINT `onboarding_tasks_checklist_id_foreign` FOREIGN KEY (`checklist_id`) REFERENCES `onboarding_checklists` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `employee_onboarding` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) unsigned NOT NULL,
  `checklist_id` bigint(20) unsigned NOT NULL,
  `start_date` date NOT NULL,
  `expected_completion_date` date DEFAULT NULL,
  `actual_completion_date` date DEFAULT NULL,
  `status` enum('Not Started','In Progress','Completed','On Hold') DEFAULT 'Not Started',
  `completion_percentage` decimal(5,2) DEFAULT 0.00,
  `assigned_to` bigint(20) unsigned DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_onboarding_employee_id_foreign` (`employee_id`),
  KEY `employee_onboarding_checklist_id_foreign` (`checklist_id`),
  KEY `employee_onboarding_assigned_to_foreign` (`assigned_to`),
  CONSTRAINT `employee_onboarding_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `employee_onboarding_checklist_id_foreign` FOREIGN KEY (`checklist_id`) REFERENCES `onboarding_checklists` (`id`) ON DELETE CASCADE,
  CONSTRAINT `employee_onboarding_assigned_to_foreign` FOREIGN KEY (`assigned_to`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `employee_onboarding_tasks` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_onboarding_id` bigint(20) unsigned NOT NULL,
  `task_id` bigint(20) unsigned NOT NULL,
  `status` enum('Pending','In Progress','Completed','Skipped') DEFAULT 'Pending',
  `completed_by` bigint(20) unsigned DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_onboarding_tasks_emp_onboarding_id_foreign` (`employee_onboarding_id`),
  KEY `employee_onboarding_tasks_task_id_foreign` (`task_id`),
  KEY `employee_onboarding_tasks_completed_by_foreign` (`completed_by`),
  CONSTRAINT `employee_onboarding_tasks_emp_onboarding_id_foreign` FOREIGN KEY (`employee_onboarding_id`) REFERENCES `employee_onboarding` (`id`) ON DELETE CASCADE,
  CONSTRAINT `employee_onboarding_tasks_task_id_foreign` FOREIGN KEY (`task_id`) REFERENCES `onboarding_tasks` (`id`) ON DELETE CASCADE,
  CONSTRAINT `employee_onboarding_tasks_completed_by_foreign` FOREIGN KEY (`completed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Performance & KPI Tables
CREATE TABLE IF NOT EXISTS `performance_kpis` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `code` varchar(50) UNIQUE NOT NULL,
  `description` text DEFAULT NULL,
  `category` enum('Quality','Productivity','Efficiency','Customer Satisfaction','Innovation','Leadership','Teamwork','Other') DEFAULT 'Productivity',
  `measurement_type` enum('Percentage','Number','Rating','Yes/No') DEFAULT 'Percentage',
  `target_value` decimal(10,2) DEFAULT NULL,
  `unit` varchar(50) DEFAULT NULL,
  `weight` decimal(5,2) DEFAULT 10.00 COMMENT 'Weight in evaluation',
  `department_id` bigint(20) unsigned DEFAULT NULL,
  `designation_id` bigint(20) unsigned DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `performance_kpis_department_id_foreign` (`department_id`),
  KEY `performance_kpis_designation_id_foreign` (`designation_id`),
  CONSTRAINT `performance_kpis_department_id_foreign` FOREIGN KEY (`department_id`) REFERENCES `departments` (`id`) ON DELETE SET NULL,
  CONSTRAINT `performance_kpis_designation_id_foreign` FOREIGN KEY (`designation_id`) REFERENCES `designations` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `performance_reviews` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) unsigned NOT NULL,
  `reviewer_id` bigint(20) unsigned NOT NULL,
  `review_period_start` date NOT NULL,
  `review_period_end` date NOT NULL,
  `review_type` enum('Probation','Annual','Mid-Year','Quarterly','Project-Based') DEFAULT 'Annual',
  `overall_rating` decimal(3,2) DEFAULT NULL COMMENT '1-5 rating',
  `strengths` text DEFAULT NULL,
  `areas_for_improvement` text DEFAULT NULL,
  `achievements` text DEFAULT NULL,
  `goals_for_next_period` text DEFAULT NULL,
  `comments` text DEFAULT NULL,
  `status` enum('Draft','Submitted','Under Review','Completed','Acknowledged') DEFAULT 'Draft',
  `submitted_at` timestamp NULL DEFAULT NULL,
  `completed_at` timestamp NULL DEFAULT NULL,
  `employee_acknowledged_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `performance_reviews_employee_id_foreign` (`employee_id`),
  KEY `performance_reviews_reviewer_id_foreign` (`reviewer_id`),
  CONSTRAINT `performance_reviews_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `performance_reviews_reviewer_id_foreign` FOREIGN KEY (`reviewer_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `performance_review_kpis` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `review_id` bigint(20) unsigned NOT NULL,
  `kpi_id` bigint(20) unsigned NOT NULL,
  `target_value` decimal(10,2) DEFAULT NULL,
  `achieved_value` decimal(10,2) DEFAULT NULL,
  `rating` decimal(3,2) DEFAULT NULL,
  `comments` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `performance_review_kpis_review_id_foreign` (`review_id`),
  KEY `performance_review_kpis_kpi_id_foreign` (`kpi_id`),
  CONSTRAINT `performance_review_kpis_review_id_foreign` FOREIGN KEY (`review_id`) REFERENCES `performance_reviews` (`id`) ON DELETE CASCADE,
  CONSTRAINT `performance_review_kpis_kpi_id_foreign` FOREIGN KEY (`kpi_id`) REFERENCES `performance_kpis` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Training & Development Tables
CREATE TABLE IF NOT EXISTS `training_programs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `program_code` varchar(50) UNIQUE NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text DEFAULT NULL,
  `category` enum('Technical','Soft Skills','Leadership','Compliance','Safety','Product','Other') DEFAULT 'Technical',
  `training_type` enum('Classroom','Online','On-the-Job','Workshop','Seminar','Conference','Certification') DEFAULT 'Classroom',
  `trainer_name` varchar(200) DEFAULT NULL,
  `trainer_type` enum('Internal','External','Online Platform') DEFAULT 'Internal',
  `duration_days` decimal(5,2) DEFAULT NULL,
  `duration_hours` decimal(6,2) DEFAULT NULL,
  `max_participants` int(11) DEFAULT NULL,
  `cost_per_participant` decimal(10,2) DEFAULT 0.00,
  `venue` varchar(255) DEFAULT NULL,
  `start_date` date DEFAULT NULL,
  `end_date` date DEFAULT NULL,
  `enrollment_deadline` date DEFAULT NULL,
  `prerequisites` text DEFAULT NULL,
  `objectives` text DEFAULT NULL,
  `status` enum('Planned','Open for Enrollment','In Progress','Completed','Cancelled') DEFAULT 'Planned',
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `training_enrollments` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `training_program_id` bigint(20) unsigned NOT NULL,
  `employee_id` bigint(20) unsigned NOT NULL,
  `enrollment_date` date NOT NULL,
  `status` enum('Enrolled','Attended','Completed','Cancelled','Failed','Absent') DEFAULT 'Enrolled',
  `attendance_percentage` decimal(5,2) DEFAULT NULL,
  `assessment_score` decimal(5,2) DEFAULT NULL,
  `certificate_issued` tinyint(1) DEFAULT 0,
  `certificate_number` varchar(100) DEFAULT NULL,
  `certificate_date` date DEFAULT NULL,
  `feedback_rating` decimal(3,2) DEFAULT NULL COMMENT '1-5 rating',
  `feedback_comments` text DEFAULT NULL,
  `completion_date` date DEFAULT NULL,
  `cost_incurred` decimal(10,2) DEFAULT 0.00,
  `approved_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `training_enrollments_unique` (`training_program_id`,`employee_id`),
  KEY `training_enrollments_employee_id_foreign` (`employee_id`),
  KEY `training_enrollments_approved_by_foreign` (`approved_by`),
  CONSTRAINT `training_enrollments_training_program_id_foreign` FOREIGN KEY (`training_program_id`) REFERENCES `training_programs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `training_enrollments_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `training_enrollments_approved_by_foreign` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `employee_skills` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) unsigned NOT NULL,
  `skill_name` varchar(200) NOT NULL,
  `skill_category` enum('Technical','Soft Skills','Language','Certification','Tool/Software','Domain Knowledge') DEFAULT 'Technical',
  `proficiency_level` enum('Beginner','Intermediate','Advanced','Expert') DEFAULT 'Beginner',
  `years_of_experience` decimal(5,2) DEFAULT NULL,
  `last_used_date` date DEFAULT NULL,
  `acquired_through` enum('Education','Work Experience','Training','Certification','Self-Learning') DEFAULT 'Work Experience',
  `certification_name` varchar(255) DEFAULT NULL,
  `certification_date` date DEFAULT NULL,
  `expiry_date` date DEFAULT NULL,
  `is_verified` tinyint(1) DEFAULT 0,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `employee_skills_employee_id_foreign` (`employee_id`),
  CONSTRAINT `employee_skills_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Shift Scheduling Enhancement
CREATE TABLE IF NOT EXISTS `shift_schedules` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `employee_id` bigint(20) unsigned NOT NULL,
  `shift_id` bigint(20) unsigned NOT NULL,
  `schedule_date` date NOT NULL,
  `is_overtime` tinyint(1) DEFAULT 0,
  `status` enum('Scheduled','Confirmed','Cancelled','Swapped') DEFAULT 'Scheduled',
  `notes` text DEFAULT NULL,
  `created_by` bigint(20) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `shift_schedules_unique` (`employee_id`,`schedule_date`),
  KEY `shift_schedules_shift_id_foreign` (`shift_id`),
  KEY `shift_schedules_created_by_foreign` (`created_by`),
  CONSTRAINT `shift_schedules_employee_id_foreign` FOREIGN KEY (`employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shift_schedules_shift_id_foreign` FOREIGN KEY (`shift_id`) REFERENCES `shifts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shift_schedules_created_by_foreign` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `shift_swap_requests` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `requestor_id` bigint(20) unsigned NOT NULL,
  `requestor_schedule_id` bigint(20) unsigned NOT NULL,
  `requested_employee_id` bigint(20) unsigned NOT NULL,
  `requested_schedule_id` bigint(20) unsigned NOT NULL,
  `reason` text DEFAULT NULL,
  `status` enum('Pending','Approved','Rejected','Cancelled') DEFAULT 'Pending',
  `approved_by` bigint(20) unsigned DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `shift_swap_requests_requestor_id_foreign` (`requestor_id`),
  KEY `shift_swap_requests_requested_employee_id_foreign` (`requested_employee_id`),
  KEY `shift_swap_requests_approved_by_foreign` (`approved_by`),
  CONSTRAINT `shift_swap_requests_requestor_id_foreign` FOREIGN KEY (`requestor_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shift_swap_requests_requested_employee_id_foreign` FOREIGN KEY (`requested_employee_id`) REFERENCES `employees` (`id`) ON DELETE CASCADE,
  CONSTRAINT `shift_swap_requests_approved_by_foreign` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
